export type RouteMaturityClass =
  | 'runtime-backed'
  | 'runtime-degraded'
  | 'informational'
  | 'demo'
  | 'local-only'
  | 'unavailable';

export type RuntimeDependencyClass = 'none' | 'auth' | 'backend' | 'auth+backend' | 'local-runtime';
export type RouteUiMode = 'operational' | 'restricted' | 'informational';
export type NavStatus = 'primary' | 'degraded' | 'demo' | 'info';

export interface RouteMaturityRecord {
  path: string;
  navGroup: 'platform' | 'operations' | 'support';
  navLabel: string;
  maturity: RouteMaturityClass;
  runtimeDependency: RuntimeDependencyClass;
  authRequired: boolean;
  backendRequired: boolean;
  disclosureRequired: boolean;
  navStatus: NavStatus;
  ctaRestriction: 'none' | 'no-destructive' | 'read-only';
  degradedBehavior: string;
  uiMode: RouteUiMode;
  summary: string;
}

export const routeMaturityCatalog: readonly RouteMaturityRecord[] = [
  {
    path: '/console',
    navGroup: 'platform',
    navLabel: 'Console',
    maturity: 'runtime-degraded',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: false,
    navStatus: 'degraded',
    ctaRestriction: 'read-only',
    degradedBehavior: 'Redirects to overview and preserves explicit backend missing disclosure when runtime wiring is absent.',
    uiMode: 'operational',
    summary: 'Authenticated console entry route.',
  },
  {
    path: '/console/overview',
    navGroup: 'platform',
    navLabel: 'Overview',
    maturity: 'runtime-degraded',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: true,
    navStatus: 'degraded',
    ctaRestriction: 'read-only',
    degradedBehavior: 'Shows explicit standby metrics and backend wiring guidance when REQUIEM_API_URL is absent.',
    uiMode: 'operational',
    summary: 'Control plane landing page with truthful standby behavior.',
  },
  {
    path: '/console/architecture',
    navGroup: 'platform',
    navLabel: 'Architecture',
    maturity: 'runtime-degraded',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: true,
    navStatus: 'degraded',
    ctaRestriction: 'read-only',
    degradedBehavior: 'Displays dependency checks and unavailability states instead of fabricated health.',
    uiMode: 'operational',
    summary: 'Runtime architecture and dependency diagnostics.',
  },
  {
    path: '/console/guarantees',
    navGroup: 'platform',
    navLabel: 'Guarantees',
    maturity: 'runtime-degraded',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: true,
    navStatus: 'degraded',
    ctaRestriction: 'read-only',
    degradedBehavior: 'Shows static guarantee definitions plus local status when live checks are unavailable.',
    uiMode: 'operational',
    summary: 'Verification guarantees with bounded live status.',
  },
  {
    path: '/console/replication',
    navGroup: 'platform',
    navLabel: 'Replication',
    maturity: 'informational',
    runtimeDependency: 'none',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: true,
    navStatus: 'info',
    ctaRestriction: 'read-only',
    degradedBehavior: 'Always renders informational-only topology and synthetic telemetry.',
    uiMode: 'informational',
    summary: 'Reference-only replication concepts and topology.',
  },
  {
    path: '/console/logs',
    navGroup: 'operations',
    navLabel: 'Logs',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Returns empty/degraded state when backend is unreachable.',
    uiMode: 'operational',
    summary: 'Primary runtime operational evidence for logs.',
  },
  {
    path: '/console/runs',
    navGroup: 'operations',
    navLabel: 'Runs',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Shows fetch failure or empty-state messaging when runtime data is unavailable.',
    uiMode: 'operational',
    summary: 'Primary deterministic execution evidence surface.',
  },
  {
    path: '/console/plans',
    navGroup: 'operations',
    navLabel: 'Plans',
    maturity: 'demo',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: true,
    navStatus: 'demo',
    ctaRestriction: 'no-destructive',
    degradedBehavior: 'Uses demo-safe API responses; not proof of live orchestration.',
    uiMode: 'restricted',
    summary: 'Demo-backed plan workflow verification route.',
  },
  {
    path: '/console/policies',
    navGroup: 'operations',
    navLabel: 'Policies',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Displays runtime-backed policy telemetry, degraded when backend is unreachable.',
    uiMode: 'operational',
    summary: 'Policy runtime and control operations.',
  },
  {
    path: '/console/capabilities',
    navGroup: 'operations',
    navLabel: 'Capabilities',
    maturity: 'runtime-backed',
    runtimeDependency: 'auth+backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Auth or backend gaps surface as restricted/degraded capability state.',
    uiMode: 'operational',
    summary: 'Capability and token management surface.',
  },
  {
    path: '/console/finops',
    navGroup: 'operations',
    navLabel: 'FinOps',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Shows guarded budget views when backend feeds are absent.',
    uiMode: 'operational',
    summary: 'Cost and budget operational surface.',
  },
  {
    path: '/console/snapshots',
    navGroup: 'operations',
    navLabel: 'Snapshots',
    maturity: 'demo',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: true,
    navStatus: 'demo',
    ctaRestriction: 'no-destructive',
    degradedBehavior: 'Snapshot listing/restore is demo-safe and must not imply production rollback.',
    uiMode: 'restricted',
    summary: 'Demo-backed snapshot workflow checks.',
  },
  {
    path: '/console/objects',
    navGroup: 'operations',
    navLabel: 'Objects',
    maturity: 'runtime-degraded',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: false,
    navStatus: 'degraded',
    ctaRestriction: 'read-only',
    degradedBehavior: 'Object inventory remains read-only and discloses missing runtime indexing when backend feeds are unavailable.',
    uiMode: 'restricted',
    summary: 'Object evidence browser with explicit degraded semantics.',
  },
  {
    path: '/console/decisions',
    navGroup: 'operations',
    navLabel: 'Decisions',
    maturity: 'runtime-degraded',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: false,
    navStatus: 'degraded',
    ctaRestriction: 'read-only',
    degradedBehavior: 'Decision traces render as read-only evidence and stay explicit when backend enrichment is unavailable.',
    uiMode: 'restricted',
    summary: 'Decision lineage and policy reasoning evidence.',
  },
  {
    path: '/app',
    navGroup: 'platform',
    navLabel: 'App',
    maturity: 'runtime-degraded',
    runtimeDependency: 'auth+backend',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: false,
    navStatus: 'degraded',
    ctaRestriction: 'read-only',
    degradedBehavior: 'Authenticated app shell remains available but runtime-backed panels disclose degraded backend/auth states.',
    uiMode: 'restricted',
    summary: 'Authenticated control plane shell and section redirect.',
  },
  {
    path: '/app/executions',
    navGroup: 'operations',
    navLabel: 'Executions',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Execution table degrades to explicit unavailable/no-data state when backend execution feeds cannot be queried.',
    uiMode: 'operational',
    summary: 'Deterministic execution evidence and replay linkage.',
  },
  {
    path: '/app/semantic-ledger',
    navGroup: 'operations',
    navLabel: 'Semantic Ledger',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Ledger evidence reports backend fetch errors explicitly instead of fabricating chain continuity.',
    uiMode: 'operational',
    summary: 'Semantic ledger and provenance inspection.',
  },
  {
    path: '/app/replay',
    navGroup: 'operations',
    navLabel: 'Replay',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Replay controls are disabled with concrete backend dependency messaging when runtime replay is unavailable.',
    uiMode: 'operational',
    summary: 'Replay execution and artifact evidence surface.',
  },
  {
    path: '/app/cas',
    navGroup: 'operations',
    navLabel: 'CAS',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'CAS operations surface backend unavailability and no-data states distinctly for storage evidence.',
    uiMode: 'operational',
    summary: 'Content-addressed storage integrity and retrieval.',
  },
  {
    path: '/app/policy',
    navGroup: 'operations',
    navLabel: 'Policy Engine',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Policy controls remain explicit about backend unreachable/forbidden states before allowing updates.',
    uiMode: 'operational',
    summary: 'Policy enforcement and evaluation configuration.',
  },
  {
    path: '/app/audit',
    navGroup: 'operations',
    navLabel: 'Audit Ledger',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Audit evidence fetches declare unavailable/no-data outcomes explicitly when log backend is degraded.',
    uiMode: 'operational',
    summary: 'Audit and provenance ledger route.',
  },
  {
    path: '/app/metrics',
    navGroup: 'operations',
    navLabel: 'Observability',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Observability route distinguishes empty telemetry from backend unavailability.',
    uiMode: 'operational',
    summary: 'Runtime metrics and diagnostics trends.',
  },
  {
    path: '/app/diagnostics',
    navGroup: 'operations',
    navLabel: 'Diagnostics',
    maturity: 'runtime-degraded',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: false,
    navStatus: 'degraded',
    ctaRestriction: 'read-only',
    degradedBehavior: 'Runtime diagnostics emit backend configured/unconfigured status and disable remediation controls when prerequisites are missing.',
    uiMode: 'restricted',
    summary: 'Doctor checks and diagnostic status route.',
  },
  {
    path: '/app/interop',
    navGroup: 'operations',
    navLabel: 'Interop',
    maturity: 'runtime-degraded',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: false,
    navStatus: 'degraded',
    ctaRestriction: 'read-only',
    degradedBehavior: 'Interop actions remain local-only or disabled with explicit backend dependency annotations.',
    uiMode: 'restricted',
    summary: 'Integration and interoperability readiness checks.',
  },
  {
    path: '/app/tenants',
    navGroup: 'operations',
    navLabel: 'Tenants',
    maturity: 'runtime-backed',
    runtimeDependency: 'auth+backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Tenant isolation evidence distinguishes auth failures, backend unreachable states, and empty tenancy data.',
    uiMode: 'operational',
    summary: 'Tenant-isolation evidence and controls.',
  },
  {
    path: '/intelligence/learning',
    navGroup: 'operations',
    navLabel: 'Learning',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Learning telemetry declares backend/no-data states explicitly before exposing runtime metrics.',
    uiMode: 'operational',
    summary: 'Learning loop and model telemetry route.',
  },
  {
    path: '/intelligence/signals',
    navGroup: 'operations',
    navLabel: 'Signals',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Signals view preserves explicit backend and no-data state distinctions.',
    uiMode: 'operational',
    summary: 'Operational signals and event intelligence.',
  },
  {
    path: '/intelligence/cases',
    navGroup: 'operations',
    navLabel: 'Cases',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Case review surfaces backend unreachable and forbidden states with explicit triage guidance.',
    uiMode: 'operational',
    summary: 'Case extraction and review evidence route.',
  },
  {
    path: '/intelligence/verification',
    navGroup: 'operations',
    navLabel: 'Verification',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Verification status clearly reports runtime unavailability vs no violations detected.',
    uiMode: 'operational',
    summary: 'Verification reports and controls.',
  },
  {
    path: '/intelligence/calibration',
    navGroup: 'operations',
    navLabel: 'Calibration',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Calibration charts disclose backend dependency and no-data status before presenting confidence outputs.',
    uiMode: 'operational',
    summary: 'Calibration windows and confidence monitoring.',
  },
  {
    path: '/intelligence/foundry',
    navGroup: 'operations',
    navLabel: 'Foundry',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Foundry datasets/runs disclose backend configuration and availability before enabling runtime actions.',
    uiMode: 'operational',
    summary: 'Foundry dataset generation and execution route.',
  },
  {
    path: '/registry',
    navGroup: 'operations',
    navLabel: 'Registry',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Empty state is explicit when object metadata indexing is unavailable.',
    uiMode: 'operational',
    summary: 'Registry object and package evidence surface.',
  },
  {
    path: '/spend',
    navGroup: 'operations',
    navLabel: 'Spend',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Uses explicit no-data and backend-degraded status states.',
    uiMode: 'operational',
    summary: 'Spend and policy cost management.',
  },
  {
    path: '/drift',
    navGroup: 'operations',
    navLabel: 'Drift',
    maturity: 'runtime-backed',
    runtimeDependency: 'backend',
    authRequired: true,
    backendRequired: true,
    disclosureRequired: false,
    navStatus: 'primary',
    ctaRestriction: 'none',
    degradedBehavior: 'Shows deterministic drift health and explicit unavailability messaging.',
    uiMode: 'operational',
    summary: 'Drift intelligence and variance analysis.',
  },
  {
    path: '/settings',
    navGroup: 'operations',
    navLabel: 'Settings',
    maturity: 'runtime-degraded',
    runtimeDependency: 'auth',
    authRequired: true,
    backendRequired: false,
    disclosureRequired: false,
    navStatus: 'degraded',
    ctaRestriction: 'read-only',
    degradedBehavior: 'Restricts settings actions when auth runtime is unavailable.',
    uiMode: 'restricted',
    summary: 'Settings route with auth-bound operational controls.',
  },
] as const;

export const routeMaturityByPath = Object.fromEntries(
  routeMaturityCatalog.map((route) => [route.path, route]),
) as Record<string, RouteMaturityRecord>;

export function getRouteMaturity(path: string): RouteMaturityRecord {
  const route = routeMaturityByPath[path];
  if (!route) {
    throw new Error(`No maturity definition found for route: ${path}`);
  }
  return route;
}

export function maturityNoteTone(maturity: RouteMaturityClass): 'runtime' | 'runtime-degraded' | 'demo' | 'informational' {
  if (maturity === 'runtime-backed') return 'runtime';
  if (maturity === 'runtime-degraded') return 'runtime-degraded';
  if (maturity === 'demo') return 'demo';
  return 'informational';
}
