#!/usr/bin/env node
/**
 * @fileoverview Completion command - Generate shell completion scripts.
 *
 * Supports:
 * - bash: Bash shell completion
 * - zsh: Zsh shell completion
 * - fish: Fish shell completion
 * - pwsh: PowerShell completion
 *
 * Usage:
 *   requiem completion bash > /etc/bash_completion.d/requiem
 *   requiem completion zsh > ~/.zsh/completions/_requiem
 *   requiem completion fish > ~/.config/fish/completions/requiem.fish
 */

import { Command } from 'commander';

const VERSION = '0.2.0';

const BASH_COMPLETION = `#!/bin/bash
# Requiem CLI Bash Completion
# Generated by requiem completion bash

_requiem() {
  local cur prev opts
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  # Main commands
  opts="
    run verify replay fingerprint ui quickstart
    tool trace stats status telemetry doctor bugreport
    init config backup restore import nuke
    learn realign pivot rollback symmetry economics
    diff lineage simulate drift explain usage tenant-check chaos share
    decide junctions agent ai selftest
    logs list show search completion whoami connect
    help version
  "

  # Subcommands for specific commands
  case "${prev}" in
    replay)
      opts="run diff"
      ;;
    tool)
      opts="list exec"
      ;;
    decide)
      opts="evaluate explain outcome"
      ;;
    junctions)
      opts="scan"
      ;;
    agent)
      opts="serve"
      ;;
    ai)
      opts="tools skills"
      ;;
    list)
      opts="runs artifacts policies providers"
      ;;
    show)
      opts="run artifact manifest"
      ;;
    search)
      opts="fingerprint error tool"
      ;;
    completion)
      opts="bash zsh fish pwsh"
      ;;
    connect)
      opts="test status"
      ;;
    logs)
      opts="tail follow"
      ;;
    -f|--format|--output)
      opts="json jsonl table yaml"
      ;;
    --level)
      opts="error warn info debug"
      ;;
    *)
      ;;
  esac

  COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
  return 0
}

complete -F _requiem requiem
complete -F _requiem reach
`;

const ZSH_COMPLETION = `# Requiem CLI Zsh Completion
# Generated by requiem completion zsh

_requiem() {
  local -a commands
  commands=(
    'run:Execute a tool with determinism proof'
    'verify:Verify execution determinism'
    'replay:Replay execution with verification'
    'fingerprint:Generate shareable execution proof'
    'ui:Launch web dashboard'
    'quickstart:10-minute proof flow'
    'tool:Tool management'
    'trace:Visualize decision trace'
    'stats:Determinism metrics'
    'status:System health'
    'telemetry:Real-time usage stats'
    'doctor:Validate environment'
    'bugreport:Diagnostic report'
    'init:Initialize configuration'
    'config:Manage configuration'
    'backup:Dump database'
    'restore:Restore database'
    'import:Ingest logs'
    'nuke:Clear state'
    'logs:View and filter logs'
    'list:List runs artifacts policies providers'
    'show:Show run artifact manifest details'
    'search:Search runs by criteria'
    'completion:Generate shell completion'
    'whoami:Show entitlements context'
    'connect:Test connectivity'
    'help:Show help'
    'version:Show version'
  )

  local -a replay_commands
  replay_commands=(
    'run:Replay a specific run'
    'diff:Compare two runs'
  )

  local -a tool_commands
  tool_commands=(
    'list:List registered tools'
    'exec:Execute a tool'
  )

  local -a list_commands
  list_commands=(
    'runs:List execution runs'
    'artifacts:List stored artifacts'
    'policies:List available policies'
    'providers:List configured providers'
  )

  local -a show_commands
  show_commands=(
    'run:Show run details'
    'artifact:Show artifact details'
    'manifest:Show manifest details'
  )

  local -a search_commands
  search_commands=(
    'fingerprint:Search by fingerprint'
    'error:Search by error code'
    'tool:Search by tool name'
  )

  local -a completion_commands
  completion_commands=(
    'bash:Generate bash completion'
    'zsh:Generate zsh completion'
    'fish:Generate fish completion'
    'pwsh:Generate PowerShell completion'
  )

  local -a connect_commands
  connect_commands=(
    'test:Test connectivity'
    'show:Show connectivity status'
  )

  local -a logs_commands
  logs_commands=(
    'tail:Tail recent logs'
    'follow:Follow logs in real-time'
  )

  local -a connect_commands
  connect_commands=(
    'test:Test connectivity'
    'status:Show provider status'
  )

  _describe 'command' commands
  _describe 'subcommand' replay_commands
  _describe 'subcommand' tool_commands
  _describe 'subcommand' list_commands
  _describe 'subcommand' show_commands
  _describe 'subcommand' search_commands
  _describe 'subcommand' completion_commands
  _describe 'subcommand' connect_commands
  _describe 'subcommand' logs_commands
}

_requiem "$@"
`;

const FISH_COMPLETION = `# Requiem CLI Fish Completion
# Generated by requiem completion fish

complete -c requiem -f -n '__fish_use_subcommand' -a 'run' -d 'Execute a tool with determinism proof'
complete -c requiem -f -n '__fish_use_subcommand' -a 'verify' -d 'Verify execution determinism'
complete -c requiem -f -n '__fish_use_subcommand' -a 'replay' -d 'Replay execution with verification'
complete -c requiem -f -n '__fish_use_subcommand' -a 'fingerprint' -d 'Generate shareable execution proof'
complete -c requiem -f -n '__fish_use_subcommand' -a 'ui' -d 'Launch web dashboard'
complete -c requiem -f -n '__fish_use_subcommand' -a 'quickstart' -d '10-minute proof flow'
complete -c requiem -f -n '__fish_use_subcommand' -a 'tool' -d 'Tool management'
complete -c requiem -f -n '__fish_use_subcommand' -a 'trace' -d 'Visualize decision trace'
complete -c requiem -f -n '__fish_use_subcommand' -a 'stats' -d 'Determinism metrics'
complete -c requiem -f -n '__fish_use_subcommand' -a 'status' -d 'System health'
complete -c requiem -f -n '__fish_use_subcommand' -a 'telemetry' -d 'Real-time usage stats'
complete -c requiem -f -n '__fish_use_subcommand' -a 'doctor' -d 'Validate environment'
complete -c requiem -f -n '__fish_use_subcommand' -a 'bugreport' -d 'Diagnostic report'
complete -c requiem -f -n '__fish_use_subcommand' -a 'init' -d 'Initialize configuration'
complete -c requiem -f -n '__fish_use_subcommand' -a 'config' -d 'Manage configuration'
complete -c requiem -f -n '__fish_use_subcommand' -a 'backup' -d 'Dump database'
complete -c requiem -f -n '__fish_use_subcommand' -a 'restore' -d 'Restore database'
complete -c requiem -f -n '__fish_use_subcommand' -a 'import' -d 'Ingest logs'
complete -c requiem -f -n '__fish_use_subcommand' -a 'nuke' -d 'Clear state'
complete -c requiem -f -n '__fish_use_subcommand' -a 'logs' -d 'View and filter logs'
complete -c requiem -f -n '__fish_use_subcommand' -a 'list' -d 'List runs artifacts policies providers'
complete -c requiem -f -n '__fish_use_subcommand' -a 'show' -d 'Show run artifact manifest details'
complete -c requiem -f -n '__fish_use_subcommand' -a 'search' -d 'Search runs by criteria'
complete -c requiem -f -n '__fish_use_subcommand' -a 'completion' -d 'Generate shell completion'
complete -c requiem -f -n '__fish_use_subcommand' -a 'whoami' -d 'Show entitlements context'
complete -c requiem -f -n '__fish_use_subcommand' -a 'connect' -d 'Test connectivity'
complete -c requiem -f -n '__fish_use_subcommand' -a 'help' -d 'Show help'
complete -c requiem -f -n '__fish_use_subcommand' -a 'version' -d 'Show version'

# Global flags
complete -c requiem -f -l 'json' -d 'Output in JSON format'
complete -c requiem -f -l 'jsonl' -d 'Output in JSONL format'
complete -c requiem -f -l 'format' -d 'Output format: json, jsonl, table'
complete -c requiem -f -l 'help' -d 'Show help'
complete -c requiem -f -l 'version' -d 'Show version'
`;

const POWERSHELL_COMPLETION = `# Requiem CLI PowerShell Completion
# Generated by requiem completion pwsh

$script:RequiemCommands = @(
  @{ Name = 'run'; Description = 'Execute a tool with determinism proof' }
  @{ Name = 'verify'; Description = 'Verify execution determinism' }
  @{ Name = 'replay'; Description = 'Replay execution with verification' }
  @{ Name = 'fingerprint'; Description = 'Generate shareable execution proof' }
  @{ Name = 'ui'; Description = 'Launch web dashboard' }
  @{ Name = 'quickstart'; Description = '10-minute proof flow' }
  @{ Name = 'tool'; Description = 'Tool management' }
  @{ Name = 'trace'; Description = 'Visualize decision trace' }
  @{ Name = 'stats'; Description = 'Determinism metrics' }
  @{ Name = 'status'; Description = 'System health' }
  @{ Name = 'telemetry'; Description = 'Real-time usage stats' }
  @{ Name = 'doctor'; Description = 'Validate environment' }
  @{ Name = 'bugreport'; Description = 'Diagnostic report' }
  @{ Name = 'init'; Description = 'Initialize configuration' }
  @{ Name = 'config'; Description = 'Manage configuration' }
  @{ Name = 'backup'; Description = 'Dump database' }
  @{ Name = 'restore'; Description = 'Restore database' }
  @{ Name = 'import'; Description = 'Ingest logs' }
  @{ Name = 'nuke'; Description = 'Clear state' }
  @{ Name = 'logs'; Description = 'View and filter logs' }
  @{ Name = 'list'; Description = 'List runs artifacts policies providers' }
  @{ Name = 'show'; Description = 'Show run artifact manifest details' }
  @{ Name = 'search'; Description = 'Search runs by criteria' }
  @{ Name = 'completion'; Description = 'Generate shell completion' }
  @{ Name = 'whoami'; Description = 'Show entitlements context' }
  @{ Name = 'connect'; Description = 'Test connectivity' }
  @{ Name = 'help'; Description = 'Show help' }
  @{ Name = 'version'; Description = 'Show version' }
)

$script:RequiemFlags = @(
  @{ Name = '--json'; Description = 'Output in JSON format' }
  @{ Name = '--jsonl'; Description = 'Output in JSONL format' }
  @{ Name = '--format'; Description = 'Output format: json, jsonl, table' }
  @{ Name = '--help'; Description = 'Show help' }
  @{ Name = '--version'; Description = 'Show version' }
)

function Get-RequiemCompletion {
  param(
    [string]$Word,
    [int]$CursorPosition
  )

  $results = @()

  # Check if we're at command position
  if ($Word -match '^(requiem|reach)$' -or $Word -eq '') {
    $results += $script:RequiemCommands | ForEach-Object {
      [System.Management.Automation.CompletionResult]::new(
        $_.Name,
        $_.Name,
        'Parameter',
        $_.Description
      )
    }
  }

  # Check for flags
  if ($Word.StartsWith('-')) {
    $results += $script:RequiemFlags | Where-Object { $_.Name -like "$Word*" } | ForEach-Object {
      [System.Management.Automation.CompletionResult]::new(
        $_.Name,
        $_.Name,
        'Parameter',
        $_.Description
      )
    }
  }

  return $results
}

Register-ArgumentCompleter -CommandName requiem -ScriptBlock Get-RequiemCompletion
Register-ArgumentCompleter -CommandName reach -ScriptBlock Get-RequiemCompletion
`;

export const completion = new Command('completion')
  .description('Generate shell completion scripts')
  .argument('<shell>', 'Shell type: bash, zsh, fish, pwsh')
  .action(async (shell: string) => {
    switch (shell.toLowerCase()) {
      case 'bash':
        console.log(BASH_COMPLETION);
        break;
      case 'zsh':
        console.log(ZSH_COMPLETION);
        break;
      case 'fish':
        console.log(FISH_COMPLETION);
        break;
      case 'pwsh':
        console.log(POWERSHELL_COMPLETION);
        break;
      default:
        console.error(`Unsupported shell: ${shell}`);
        console.error('Supported shells: bash, zsh, fish, pwsh');
        console.error('');
        console.error('Usage:');
        console.error('  requiem completion bash > /etc/bash_completion.d/requiem');
        console.error('  requiem completion zsh > ~/.zsh/completions/_requiem');
        console.error('  requiem completion fish > ~/.config/fish/completions/requiem.fish');
        process.exit(1);
    }
  });
